export const CANONICAL_APP_ROUTES = {
  dashboard: "/",
  aiNews: "/ai-news",
  liveMarket: "/live-market",
  execution: "/execution",
  settings: "/settings",
  ranking: "/ranking",
  knowledge: "/knowledge",
  broker: "/broker",
  aiMarket: "/ai-market",
};

export const LEGACY_ROUTE_ALIASES = [
  { from: "/paper-trading", to: CANONICAL_APP_ROUTES.execution },
  { from: "/analyze", to: CANONICAL_APP_ROUTES.aiMarket },
  { from: "/scan", to: `${CANONICAL_APP_ROUTES.ranking}?mode=scan` },
  { from: "/kpis", to: CANONICAL_APP_ROUTES.dashboard },
  { from: "/breadth", to: CANONICAL_APP_ROUTES.ranking },
  { from: "/risk", to: CANONICAL_APP_ROUTES.broker },
  { from: "/backtest", to: CANONICAL_APP_ROUTES.ranking },
  { from: "/strategy-lab", to: CANONICAL_APP_ROUTES.ranking },
  { from: "/model-lab", to: CANONICAL_APP_ROUTES.settings },
  { from: "/alerts-center", to: CANONICAL_APP_ROUTES.execution },
  { from: "/trade-journal", to: CANONICAL_APP_ROUTES.execution },
  { from: "/automation", to: CANONICAL_APP_ROUTES.settings },
  { from: "/operations", to: CANONICAL_APP_ROUTES.settings },
  { from: "/portfolio-exposure", to: CANONICAL_APP_ROUTES.broker },
  { from: "/macro", to: CANONICAL_APP_ROUTES.aiMarket },
  { from: "/fundamentals", to: CANONICAL_APP_ROUTES.aiMarket },
  { from: "/watchlist", to: CANONICAL_APP_ROUTES.ranking },
  { from: "/ai-chat", to: CANONICAL_APP_ROUTES.aiMarket },
  { from: "/multi-chart", to: CANONICAL_APP_ROUTES.liveMarket },
  { from: "/brain", to: CANONICAL_APP_ROUTES.settings },
];
