"""Canonical event topics shared across control plane and workers."""

MARKET_RAW_CANDLE_RECEIVED = "market.raw.candle.received"
MARKET_RAW_QUOTE_RECEIVED = "market.raw.quote.received"
MARKET_NORMALIZED_CANDLE_UPDATED = "market.normalized.candle.updated"
MARKET_NORMALIZED_QUOTE_UPDATED = "market.normalized.quote.updated"
FEATURE_SNAPSHOT_UPDATED = "feature.snapshot.updated"
STRATEGY_SIGNAL_PROPOSED = "strategy.signal.proposed"
RISK_SIGNAL_ACCEPTED = "risk.signal.accepted"
RISK_SIGNAL_REJECTED = "risk.signal.rejected"
EXECUTION_ORDER_INTENT_CREATED = "execution.order.intent.created"
EXECUTION_ORDER_SUBMITTED = "execution.order.submitted"
EXECUTION_ORDER_ACKNOWLEDGED = "execution.order.acknowledged"
EXECUTION_ORDER_REJECTED = "execution.order.rejected"
EXECUTION_ORDER_CANCELED = "execution.order.canceled"
EXECUTION_FILL_RECEIVED = "execution.fill.received"
PORTFOLIO_SNAPSHOT_UPDATED = "portfolio.snapshot.updated"
AI_ANALYSIS_REQUESTED = "ai.analysis.requested"
AI_ANALYSIS_COMPLETED = "ai.analysis.completed"
TRAINING_JOB_QUEUED = "training.job.queued"
TRAINING_JOB_STARTED = "training.job.started"
TRAINING_JOB_COMPLETED = "training.job.completed"
WORKFLOW_FAILED = "workflow.failed"
AUDIT_EVENT_RECORDED = "audit.event.recorded"

__all__ = [name for name in globals() if name.isupper()]
